// flow-typed signature: 1faf18bec69fb4387b16260c512b0105
// flow-typed version: <<STUB>>/id-generator_v^1.1.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'id-generator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'id-generator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'id-generator/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'id-generator/index' {
  declare module.exports: $Exports<'id-generator'>;
}
declare module 'id-generator/index.js' {
  declare module.exports: $Exports<'id-generator'>;
}
declare module 'id-generator/test/test.js' {
  declare module.exports: $Exports<'id-generator/test/test'>;
}
