// flow-typed signature: c012ac06c0676c4d0cf1fa2a7ce0d21b
// flow-typed version: <<STUB>>/jsx-loader_v^0.13.2/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsx-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsx-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jsx-loader/index' {
  declare module.exports: $Exports<'jsx-loader'>;
}
declare module 'jsx-loader/index.js' {
  declare module.exports: $Exports<'jsx-loader'>;
}
